<a href="https://colab.research.google.com/github/00hamza00/Data-Science-and-Decision-Making/blob/master/Data_Science_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Integer array 4x2

In [0]:
import numpy as np
x = np.array([[0,2],[4,6],[8,10],[12,14]])
print(x.ndim)
print(x.shape)
print(x)

2
(4, 2)
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]


# 2) Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
x = np.array([1,7,21,4,3,68,5,8,19,0])
print('ascending order : ',np.sort(x))
print('descending order : ', np.sort(x)[::-1])

ascending order :  [ 0  1  3  4  5  7  8 19 21 68]
descending order :  [68 21 19  8  7  5  4  3  1  0]


# 3) Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [0]:
x = np.array([1,2,3,4,5,6,7,8,9])
x = np.split(x,3)
print(x)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# 4) Stack two arrays of any size horizontally and vertically

In [0]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print('vertical stack : ',np.stack((x,y)))
print('horizontal stack : ',np.stack((x,y),axis = -1))

vertical stack :  [[1 2 3]
 [4 5 6]]
horizontal stack :  [[1 4]
 [2 5]
 [3 6]]


# 5) Create two array of same size and find common elements

In [0]:
x= np.array([1,2,2,3,4,11,15,17])
y= np.array([5,4,6,7,8,2,11,13])
np.intersect1d(x,y)



array([ 2,  4, 11])

# 6) Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
x = np.arange(25).reshape(5,5)
print(x)
print('max in column:  ',x.max(axis=0))
print('min in column:  ',x.min(axis=0))

for i in x:
  print('max in :  ',np.amax(i))
  print('min in :  ',np.amin(i))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
max in column:   [20 21 22 23 24]
min in column:   [0 1 2 3 4]
max in :   4
min in :   0
max in :   9
min in :   5
max in :   14
min in :   10
max in :   19
min in :   15
max in :   24
min in :   20


# 7) Create an array of size 100 and  compute the mean, median, standard deviation.

In [0]:
x = np.random.randint(200, size = 100)
print(x)
print('mean: ', np.mean(x))
print('median : ',np.median(x))
print('std deviation : ', np.std(x))

[ 44 147 132 172   0 167  80 109  56 195 169 134 195  65 117 173   0  14
 139 101 179 114  56 114  25 134  59 114 161 105  79 106   5 178 123  78
 146 127   7 107  12 131 148  36  88  28  20  29  99 132 176  57  55 191
 175 127 107 179  57 180  49  11  93  59  64 125  60 128 121 126 190 124
  85 115 132  10 149  44  11 164 144  62 138 139 140 189  64 131 112   5
  11 134  14 135  75  18  92   7 122 151]
mean:  99.96
median :  113.0
std deviation :  56.27075972474514


# 8) Normalize a 5x5 random matrix 

In [0]:
x = np.random.randint(0, 100, (5,5))
print(x)
from sklearn.preprocessing import normalize
normalized = normalize(x, axis=1, norm='l2')
print(normalized)

[[62 89  9 38 53]
 [20 33 87 66 34]
 [33 86 79 75 11]
 [88 15 39 51 10]
 [68 49 82 38 78]]
[[0.48864363 0.70144005 0.07093214 0.29949126 0.41771149]
 [0.1656915  0.27339097 0.72075801 0.54678194 0.28167554]
 [0.23063956 0.60106068 0.55213713 0.52418082 0.07687985]
 [0.7970086  0.13585374 0.35321972 0.46190271 0.09056916]
 [0.46618008 0.33592388 0.56215834 0.2605124  0.53473598]]


# 9) Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [0]:
x = np.random.randint(99, size=(4,4,3))
y = np.random.randint(99 , size = (4,4))
print(x * y[:,:,None])

[[[1612 5044 4992]
  [5915 2366 4004]
  [  44  174  172]
  [3584 1344 1008]]

 [[1365 1290 1440]
  [1768 3944 1496]
  [5037 1898 4307]
  [2184  234 5148]]

 [[2816  352   88]
  [1681 3567 2296]
  [8160 4250 4080]
  [1232  660 1760]]

 [[2640 2190 1260]
  [7560 7560 5628]
  [ 845 3315 1495]
  [2205 3330 2655]]]
